# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('batch_size', models.FloatField()),
                ('yeast', models.CharField(max_length=200)),
                ('fermentation_temp', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beers',
            },
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Beer')),
            ],
            options={
                'db_table': 'grains',
            },
        ),
        migrations.CreateModel(
            name='GrainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'grain_types',
            },
        ),
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('alpha_acid', models.FloatField()),
                ('time', models.IntegerField()),
                ('use', models.CharField(max_length=200)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Beer')),
            ],
            options={
                'db_table': 'hops',
            },
        ),
        migrations.AddField(
            model_name='grain',
            name='grain_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GrainType'),
        ),
    ]
