# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grain',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grains', to='api.Beer'),
        ),
        migrations.AlterField(
            model_name='hops',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='api.Beer'),
        ),
    ]
