# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170830_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
    ]
